name: InnovaSystems
favicon: null
layout_spectrum: 0.8668921468779445
typography_spectrum: 0.7512425174936652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#ea8529'
    - '#a2a2a2'
    - '#545454'
    - '#121212'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
