name: InnovaSystems
favicon: null
layout_spectrum: 0.8668921468779445
typography_spectrum: 0.7512425174936652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.5764346909709275
  lightness: 0.33814815734513104
  saturation: 0.8973021083511412
  rhythmicContrast: 0.3309199863579124
purpose: []
