name: InnovaSystems
favicon: null
layout_spectrum: 0.63516
typography_spectrum: 0.7512425174936652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#eca83d'
    - '#2e271c'
    - '#ffffff'
    - '#d16424'
    - '#c42003'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
